site_name: TicketFlow - Veille Technologique
site_url: https://RacGab.github.io/veille-techno-1SH/
site_description: Documentation de recherche pour le projet TicketFlow
site_author: Gabriel Racine

theme:
  name: material
  language: fr
  palette:
    primary: indigo
    accent: blue
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy

nav:
  - Accueil: index.md
  - Structure du Projet: structure.md
  - Recherche: recherche.md
  - Architecture RAG: architecture_rag.md
  - Architecture des données: database.md
  - Interface Web: interface_web.md
  - Guide Technique: basics.md

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
