"""create ticketflow core tables

Revision ID: 879fb21b383e
Revises: 
Create Date: 2026-06-01 09:15:08.371403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879fb21b383e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_modification', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('contexte_retrouve', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('score_similarite', sa.Float(), nullable=True),
    sa.Column('categorie_reference', sa.String(length=50), nullable=True),
    sa.Column('priorite_reference', sa.String(length=50), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('triage_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('categorie', sa.String(length=50), nullable=False),
    sa.Column('priorite', sa.String(length=50), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('tokens_utilises', sa.Integer(), nullable=True),
    sa.Column('modele_ia', sa.String(length=100), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('triage_results')
    op.drop_table('rag_history')
    op.drop_table('tickets')
    # ### end Alembic commands ###
